# -*- coding: utf-8 -*-
"""
A command-line tool to simplify common pre- and post-processing tasks
for the CASTEP plane-wave DFT code.
"""

import subprocess
from pathlib import Path
import shutil

import typer
from pymatgen.core.structure import Structure
from pymatgen.io.cif import CifWriter
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

# --- Typer Application Setup ---
app = typer.Typer(
    name="castep-easytool",
    help="""
    ⚛️ **castep-easytool**: A CLI to simplify CASTEP workflows.
    """,
    add_completion=False,
    rich_markup_mode="markdown"
)

# --- Helper Function for Pymatgen (used by 'convert') ---
def _read_structure(filepath: Path) -> Structure:
    """Reads a structure file and returns a Pymatgen Structure object."""
    if not filepath.exists():
        typer.secho(f"❌ Error: File not found at '{filepath}'", fg=typer.colors.RED)
        raise typer.Exit(code=1)
    try:
        return Structure.from_file(filepath)
    except Exception as e:
        typer.secho(f"❌ Error reading structure from '{filepath}': {e}", fg=typer.colors.RED)
        raise typer.Exit(code=1)

# --- Core Commands ---
@app.command()
def convert(
    filepath: Path = typer.Argument(..., help="Path to the input structure file (.cif, .cell, etc.)."),
    to: str = typer.Option("primitive", "--to", help="Target cell type: 'primitive' or 'conventional'.")
):
    """
    Convert a crystal structure between **conventional** and **primitive** cells.
    """
    if to.lower() not in ["primitive", "conventional"]:
        typer.secho("❌ Error: --to must be either 'primitive' or 'conventional'.", fg=typer.colors.RED)
        raise typer.Exit(code=1)

    typer.echo(f"📖 Reading structure from '{filepath}'...")
    struct = _read_structure(filepath)
    sga = SpacegroupAnalyzer(struct)

    output_struct, suffix = (sga.get_primitive_standard_structure(), "_primitive") if to.lower() == "primitive" else (sga.get_conventional_standard_structure(), "_conventional")
    
    typer.echo(f"🔍 Finding {to} standard structure...")
    
    output_filename = filepath.parent / f"{filepath.stem}{suffix}.cif"
    
    CifWriter(output_struct).write_file(output_filename)
    typer.secho(f"✅ Success! Wrote {to} cell to '{output_filename}'", fg=typer.colors.GREEN)

@app.command()
def kpath(
    filepath: Path = typer.Argument(..., help="Path to the input primitive cell file.")
):
    """
    Generates a CASTEP bands.cell file using sumo-kgen and moves it to the correct directory.
    """
    typer.echo(f"⚡️ Running 'sumo-kgen --code castep -p {filepath.name}'...")
    
    command = [
        "sumo-kgen", "--code", "castep", "-p", str(filepath)
    ]
    try:
        subprocess.run(
            command, capture_output=True, text=True, check=True
        )
    except FileNotFoundError:
        typer.secho("❌ Error: 'sumo-kgen' not found. Is SUMO installed and in your PATH?", fg=typer.colors.RED)
        raise typer.Exit(1)
    except subprocess.CalledProcessError as e:
        typer.secho(f"❌ Error running sumo-kgen: {e.stderr}", fg=typer.colors.RED)
        raise typer.Exit(1)

    # --- FINAL FIX: Look for the hardcoded 'band.cell' filename ---
    source_name = "band.cell"
    source_path = Path.cwd() / source_name
    
    # Define the new, more descriptive name for the destination file
    destination_name = f"{filepath.stem}_bands.cell"
    destination_path = filepath.parent / destination_name

    if not source_path.exists():
        typer.secho(f"❌ Error: Could not find '{source_name}' that sumo-kgen should have created in {Path.cwd()}.", fg=typer.colors.RED)
        raise typer.Exit(1)
    
    typer.echo(f" relocating '{source_path}' to '{destination_path}'...")
    shutil.move(str(source_path), str(destination_path))
    
    # Add the necessary TASK parameters to the top of the new file
    with open(destination_path, 'r+') as f:
        content = f.read()
        f.seek(0, 0)
        header = (
            f"# CASTEP bands.cell file generated by SUMO\n"
            f"# Relocated and formatted by castep-easytool\n\n"
            f"TASK                  : spectral\n"
            f"SPECTRAL_CALCULATION  : BANDS\n\n"
        )
        f.write(header + content)

    typer.secho(f"✅ Success! Created and moved '{destination_path}'", fg=typer.colors.GREEN)


if __name__ == "__main__":
    app()