# -*- coding: utf-8 -*-
"""
A command-line tool to simplify common pre- and post-processing tasks
for the CASTEP plane-wave DFT code.
"""
from pathlib import Path
import typer
import seekpath
from pymatgen.core.structure import Structure
from pymatgen.io.cif import CifWriter
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

app = typer.Typer(
    name="castep-easytool",
    help="⚛️ **castep-easytool**: A CLI to simplify CASTEP workflows.",
    add_completion=False,
    rich_markup_mode="markdown"
)

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _read_structure(filepath: Path) -> Structure:
    if not filepath.exists():
        typer.secho(f"❌ Error: File not found at '{filepath}'", fg=typer.colors.RED)
        raise typer.Exit(code=1)
    try:
        return Structure.from_file(filepath)
    except Exception as e:
        typer.secho(f"❌ Error reading structure from '{filepath}': {e}", fg=typer.colors.RED)
        raise typer.Exit(code=1)


def _lattice_abc_block(struct: Structure) -> str:
    a, b, c = struct.lattice.abc
    al, be, ga = struct.lattice.angles
    return (
        "%BLOCK LATTICE_ABC\n"
        f"  {a:.10f}  {b:.10f}  {c:.10f}\n"
        f"  {al:.10f}  {be:.10f}  {ga:.10f}\n"
        "%ENDBLOCK LATTICE_ABC\n"
    )


def _lattice_cart_block(struct: Structure) -> str:
    m = struct.lattice.matrix
    return (
        "%BLOCK LATTICE_CART\n"
        f"  {m[0][0]:.10f}  {m[0][1]:.10f}  {m[0][2]:.10f}\n"
        f"  {m[1][0]:.10f}  {m[1][1]:.10f}  {m[1][2]:.10f}\n"
        f"  {m[2][0]:.10f}  {m[2][1]:.10f}  {m[2][2]:.10f}\n"
        "%ENDBLOCK LATTICE_CART\n"
    )


def _positions_frac_block(struct: Structure) -> str:
    lines = ["%BLOCK POSITIONS_FRAC"]
    for site in struct:
        lines.append(f"  {site.specie.symbol:<4} {site.a:.10f}  {site.b:.10f}  {site.c:.10f}")
    lines.append("%ENDBLOCK POSITIONS_FRAC")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Command 1: convert
# ---------------------------------------------------------------------------

@app.command()
def convert(
    filepath: Path = typer.Argument(..., help="Path to the input .cif file."),
    to: str = typer.Option("primitive", "--to", help="Target cell type: 'primitive' or 'conventional'.")
):
    """
    Convert a .cif between **conventional** and **primitive** standard cells.
    """
    typer.echo(f"📖 Reading structure from '{filepath}'...")
    struct = _read_structure(filepath)
    sga = SpacegroupAnalyzer(struct)

    if to.lower() == "primitive":
        output_struct = sga.get_primitive_standard_structure()
        suffix = "_primitive"
    else:
        output_struct = sga.get_conventional_standard_structure()
        suffix = "_conventional"

    output_filename = filepath.parent / f"{filepath.stem}{suffix}.cif"
    CifWriter(output_struct).write_file(output_filename)
    typer.secho(f"✅ Wrote {to} cell to '{output_filename}'", fg=typer.colors.GREEN)


# ---------------------------------------------------------------------------
# Command 2: generate
# ---------------------------------------------------------------------------

@app.command()
def generate(
    cif_file: Path = typer.Argument(..., help="Path to the input .cif file."),
    task: str = typer.Option("GeometryOptimization", "--task", "-t", help="CASTEP task keyword.")
):
    """
    Generate a CASTEP **.cell** input file from a .cif file.
    """
    typer.echo(f"📖 Reading structure from '{cif_file}'...")
    struct = _read_structure(cif_file)

    typer.echo(f"📝 Building .cell file for task '{task}'...")
    cell_content = (
        f"# CASTEP .cell file generated by castep-easytool\n\n"
        f"TASK : {task}\n\n"
        f"{_lattice_abc_block(struct)}\n"
        f"{_positions_frac_block(struct)}"
    )

    output_filename = cif_file.parent / f"{cif_file.stem}.cell"
    output_filename.write_text(cell_content)
    typer.secho(f"✅ Wrote CASTEP input to '{output_filename}'", fg=typer.colors.GREEN)


# ---------------------------------------------------------------------------
# Command 3: bands
# ---------------------------------------------------------------------------

@app.command()
def bands(
    cif_file: Path = typer.Argument(..., help="Path to the input .cif file.")
):
    """
    Generate a CASTEP **bands.cell** file with a Seekpath BZ k-path.

    The structure is standardised to the seekpath primitive cell automatically.
    """
    typer.echo(f"📖 Reading structure from '{cif_file}'...")
    struct = _read_structure(cif_file)

    typer.echo("⚡️ Analysing structure and generating k-path with Seekpath...")
    path_data = seekpath.get_path(
        (struct.lattice.matrix, struct.frac_coords, struct.atomic_numbers),
        with_time_reversal=True
    )

    # Primitive structure from seekpath
    prim = Structure(
        lattice=path_data['primitive_lattice'],
        species=path_data['primitive_types'],
        coords=path_data['primitive_positions'],
    )

    # Build SPECTRAL_KPOINT_PATH block
    coords = path_data['point_coords']
    kpath_lines = []
    for start, end in path_data['path']:
        c = coords[start]
        kpath_lines.append(f"  {c[0]:.8f}  {c[1]:.8f}  {c[2]:.8f}  ! {start}")
    last = path_data['path'][-1][1]
    c = coords[last]
    kpath_lines.append(f"  {c[0]:.8f}  {c[1]:.8f}  {c[2]:.8f}  ! {last}")
    kpath_block = "%BLOCK SPECTRAL_KPOINT_PATH\n" + "\n".join(kpath_lines) + "\n%ENDBLOCK SPECTRAL_KPOINT_PATH\n"

    cell_content = (
        f"# CASTEP bands.cell file generated by castep-easytool (Seekpath)\n\n"
        f"TASK                  : spectral\n"
        f"SPECTRAL_CALCULATION  : BANDS\n\n"
        f"{_lattice_abc_block(prim)}\n"
        f"{_positions_frac_block(prim)}\n"
        f"{kpath_block}"
    )

    output_filename = cif_file.parent / f"{cif_file.stem}_bands.cell"
    output_filename.write_text(cell_content)
    typer.secho(f"✅ Wrote CASTEP bands input to '{output_filename}'", fg=typer.colors.GREEN)


# ---------------------------------------------------------------------------
# Command 4: geomopt
# ---------------------------------------------------------------------------

@app.command()
def geomopt(
    castep_file: Path = typer.Argument(..., help="Path to the CASTEP geometry-optimisation output (.castep) file."),
    prefix: str = typer.Option(None, "--prefix", "-p", help="Output filename stem (default: input stem).")
):
    """
    Extract the final optimised geometry from a CASTEP geometry-optimisation
    output file and write a **.cell** file ready for the next calculation.

    Supports LBFGS, BFGS, and FIRE optimisers.
    """
    import re
    import numpy as np
    from pymatgen.core import Lattice, Structure

    if not castep_file.exists():
        typer.secho(f"❌ Error: File not found at '{castep_file}'", fg=typer.colors.RED)
        raise typer.Exit(code=1)

    typer.echo(f"📖 Parsing '{castep_file}'...")
    text = castep_file.read_text(errors='replace')

    # Locate the last "Final Configuration" block for atomic positions
    config_re = re.compile(
        r'(?:LBFGS|BFGS|FIRE|GeometryOptimization): Final Configuration:',
        re.IGNORECASE
    )
    matches = list(config_re.finditer(text))
    if matches:
        tail = text[matches[-1].start():]
    else:
        unit_cell_blocks = list(re.finditer(r'^\s*Unit Cell\s*$', text, re.MULTILINE))
        if not unit_cell_blocks:
            typer.secho("❌ Cannot find any geometry block in the .castep file.", fg=typer.colors.RED)
            raise typer.Exit(code=1)
        tail = text[unit_cell_blocks[-1].start():]

    # Parse Cartesian lattice vectors from the last Unit Cell block in the file.
    # CASTEP only prints the Unit Cell block once per geometry step (not inside
    # the "Final Configuration" summary), so we search the whole file and take
    # the last occurrence.
    latt_re = re.compile(
        r'Real Lattice\(A\)[^\n]*\n'
        r'\s*([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)[^\n]*\n'
        r'\s*([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)[^\n]*\n'
        r'\s*([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)'
    )
    latt_matches = list(latt_re.finditer(text))
    if not latt_matches:
        typer.secho("❌ Cannot parse lattice vectors from the final configuration block.", fg=typer.colors.RED)
        raise typer.Exit(code=1)
    m = latt_matches[-1]
    latt_matrix = np.array([float(x) for x in m.groups()]).reshape(3, 3)

    # Parse fractional coordinates
    atom_re = re.compile(
        r'x\s+([A-Za-z]+)\s+\d+\s+([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\s+x',
        re.MULTILINE
    )
    species, frac_coords = [], []
    for am in atom_re.finditer(tail):
        species.append(am.group(1))
        frac_coords.append([float(am.group(2)), float(am.group(3)), float(am.group(4))])

    if not species:
        typer.secho("❌ Cannot parse atomic positions from the final configuration block.", fg=typer.colors.RED)
        raise typer.Exit(code=1)

    # Check convergence
    converged = bool(re.search(r'Geometry optimization completed successfully', text, re.IGNORECASE))
    iter_matches = re.findall(r'(?:LBFGS|BFGS|FIRE).*?:\s*finished iteration\s+(\d+)', text, re.IGNORECASE)
    n_iter = int(iter_matches[-1]) if iter_matches else 0

    typer.echo(f"  Species : {species}")
    typer.echo(f"  N atoms : {len(species)}")
    typer.echo(f"  Iterations: {n_iter}  |  Converged: {converged}")
    if not converged:
        typer.secho("  ⚠️  Geometry optimisation did NOT converge — using last available geometry.", fg=typer.colors.YELLOW)

    struct = Structure(
        lattice=Lattice(latt_matrix),
        species=species,
        coords=frac_coords,
        coords_are_cartesian=False,
    )

    out_stem = prefix or castep_file.stem
    output_filename = castep_file.parent / f"{out_stem}_opted.cell"

    cell_content = (
        f"# CASTEP .cell file extracted by castep-easytool from '{castep_file.name}'\n\n"
        f"{_lattice_abc_block(struct)}\n"
        f"{_positions_frac_block(struct)}\n"
    )
    output_filename.write_text(cell_content)
    typer.secho(f"✅ Written: '{output_filename}'", fg=typer.colors.GREEN)

    cif_filename = castep_file.parent / f"{out_stem}_opted.cif"
    CifWriter(struct).write_file(str(cif_filename))
    typer.secho(f"✅ Written: '{cif_filename}'", fg=typer.colors.GREEN)


# ---------------------------------------------------------------------------
# Command 5: supercell
# ---------------------------------------------------------------------------

@app.command()
def supercell(
    cell_file: Path = typer.Argument(..., help="Path to the input structure file (.cif, .cell, etc.)"),
    na: int = typer.Argument(..., help="Scale factor along a-axis."),
    nb: int = typer.Argument(None, help="Scale factor along b-axis (defaults to na)."),
    nc: int = typer.Argument(None, help="Scale factor along c-axis (defaults to na).")
):
    """
    Generate a CASTEP supercell **.cell** file from a structure file (.cif recommended).

    Examples:

      castep-easytool supercell input.cif 2

      castep-easytool supercell input.cif 2 2 1
    """
    if nb is None:
        nb = na
    if nc is None:
        nc = na
    scaling_matrix = [na, nb, nc]
    suffix = f"_{na}x{nb}x{nc}"

    typer.echo(f"📖 Reading structure from '{cell_file}'...")
    struct = _read_structure(cell_file)

    typer.echo(f"🔲 Building {suffix.lstrip('_')} supercell...")
    superstruct = struct.make_supercell(scaling_matrix)

    cell_content = (
        f"# CASTEP .cell file generated by castep-easytool\n\n"
        f"TASK : GeometryOptimization\n\n"
        f"{_lattice_cart_block(superstruct)}\n"
        f"{_positions_frac_block(superstruct)}"
    )

    output_filename = cell_file.parent / f"{cell_file.stem}{suffix}.cell"
    output_filename.write_text(cell_content)
    typer.secho(f"✅ Wrote supercell to '{output_filename}'", fg=typer.colors.GREEN)


# ---------------------------------------------------------------------------
# Command 6: bandplot
# ---------------------------------------------------------------------------

def _patch_monty():
    """Fix monty >= 2024.7.30 requiring explicit t/b mode in zopen."""
    import monty.io
    _orig = monty.io.zopen

    def _patched(filename, mode="r", **kwargs):
        if mode == "r":
            mode = "rt"
        elif mode == "w":
            mode = "wt"
        return _orig(filename, mode, **kwargs)

    monty.io.zopen = _patched
    try:
        import sumo.io.castep
        sumo.io.castep.zopen = _patched
    except ImportError:
        pass


def _kpt_label(kpt) -> str:
    label = getattr(kpt, "label", None)
    if label:
        return "Γ" if label in ("GAMMA", "G") else label
    return "?"


def _spin_gap(bs, spin) -> tuple:
    """Return (gap_ev, is_direct, transition_str) for one spin channel."""
    import numpy as np
    from pymatgen.electronic_structure.core import Spin

    bands = np.array(bs.bands[spin])   # (n_bands, n_kpoints)
    efermi = bs.efermi

    vbm_e, cbm_e = -np.inf, np.inf
    vbm_kidx, cbm_kidx = 0, 0

    for kidx in range(bands.shape[1]):
        col = bands[:, kidx]
        occ   = col[col <= efermi]
        unocc = col[col > efermi]
        if len(occ) > 0 and occ.max() > vbm_e:
            vbm_e, vbm_kidx = occ.max(), kidx
        if len(unocc) > 0 and unocc.min() < cbm_e:
            cbm_e, cbm_kidx = unocc.min(), kidx

    gap = max(0.0, cbm_e - vbm_e)
    direct = (vbm_kidx == cbm_kidx)
    vbm_lbl = _kpt_label(bs.kpoints[vbm_kidx])
    cbm_lbl = _kpt_label(bs.kpoints[cbm_kidx])
    return gap, direct, f"{vbm_lbl} → {cbm_lbl}"


def _write_bandgap_txt(bs, out_stem: str, out_dir: Path) -> None:
    from pymatgen.electronic_structure.core import Spin

    lines = [
        "Band Gap Summary",
        "=" * 40,
        f"System          : {out_stem}",
        f"Spin-polarised  : {'Yes' if bs.is_spin_polarized else 'No'}",
        "",
    ]

    def _row(label, gap, direct, trans):
        dtype = "Direct" if direct else "Indirect"
        return f"  {label:<22} {gap:.4f} eV   {dtype:<10}   {trans}"

    if bs.is_spin_polarized:
        up_gap,   up_direct,   up_trans   = _spin_gap(bs, Spin.up)
        dn_gap,   dn_direct,   dn_trans   = _spin_gap(bs, Spin.down)
        ov        = bs.get_band_gap()
        ov_gap, ov_direct, ov_trans = ov['energy'], ov['direct'], ov['transition']

        lines += [
            _row("Spin-up band gap:", up_gap, up_direct, up_trans),
            _row("Spin-down band gap:", dn_gap, dn_direct, dn_trans),
            "",
            _row("Overall band gap:", ov_gap, ov_direct, ov_trans),
        ]
    else:
        ov = bs.get_band_gap()
        lines.append(_row("Band gap:", ov['energy'], ov['direct'], ov['transition']))

    out_path = out_dir / f"{out_stem}_bandgap.txt"
    out_path.write_text("\n".join(lines) + "\n")
    typer.secho(f"✅ Written: '{out_path}'", fg=typer.colors.GREEN)
    # Echo to terminal as well
    typer.echo("\n" + "\n".join(lines))


@app.command()
def bandplot(
    bands_file: Path = typer.Argument(..., help="Path to the CASTEP .bands file."),
    cell_file: Path = typer.Option(None, "--cell", "-c",
                                   help="Path to the .cell file (default: same stem as .bands file)."),
    emin: float = typer.Option(-6.0, "--emin", help="Plot energy minimum relative to VBM (eV)."),
    emax: float = typer.Option(6.0,  "--emax", help="Plot energy maximum relative to VBM (eV)."),
    prefix: str = typer.Option(None, "--prefix", "-p",
                               help="Output filename stem (default: .bands file stem)."),
):
    """
    Plot a CASTEP band structure and write a band gap summary.

    Reads a **.bands** file produced by a CASTEP spectral/bands calculation
    and the matching **.cell** file (auto-detected by default).

    **Outputs** (written to the same folder as the .bands file):

    - `<stem>_bands.pdf` — vector plot for publications
    - `<stem>_bands.png` — raster plot for quick viewing
    - `<stem>_bandgap.txt` — band gap, direct/indirect label, transition k-points;
      spin-resolved (spin-up / spin-down / overall) for spin-polarised calculations

    **Examples:**

        castep-easytool bandplot band.bands

        castep-easytool bandplot band.bands --emin -3 --emax 3

        castep-easytool bandplot band.bands --cell Cs2SnI6_prim.cell

        castep-easytool bandplot band.bands --prefix my_calc
    """
    try:
        from sumo.io.castep import band_structure as castep_band_structure
    except ImportError as e:
        typer.secho(f"❌ Could not import sumo: {e}", fg=typer.colors.RED)
        typer.secho("   Run: pip install sumo", fg=typer.colors.RED)
        raise typer.Exit(code=1)

    try:
        from sumo.plotting.bs_plotter import SBSPlotter as SumoSBSPlotter
    except ImportError as e:
        typer.secho(f"❌ Could not import sumo plotter: {e}", fg=typer.colors.RED)
        raise typer.Exit(code=1)

    if not bands_file.exists():
        typer.secho(f"❌ File not found: '{bands_file}'", fg=typer.colors.RED)
        raise typer.Exit(code=1)

    # Resolve .cell file
    cell_path = cell_file or bands_file.with_suffix(".cell")
    if not cell_path.exists():
        typer.secho(f"❌ Cell file not found: '{cell_path}'. Use --cell to specify it.",
                    fg=typer.colors.RED)
        raise typer.Exit(code=1)

    out_stem = prefix or bands_file.stem
    out_dir  = bands_file.parent

    # Silently fix monty compatibility bug
    _patch_monty()

    typer.echo(f"📖 Reading band structure from '{bands_file}'...")
    bs = castep_band_structure(str(bands_file), cell_file=str(cell_path))

    # Band gap summary
    typer.echo("\n📊 Computing band gap...")
    _write_bandgap_txt(bs, out_stem, out_dir)

    # Plot
    typer.echo("\n🎨 Plotting band structure...")
    plotter = SumoSBSPlotter(bs)
    plt_obj = plotter.get_plot(ymin=emin, ymax=emax)

    for fmt in ("pdf", "png"):
        out_path = out_dir / f"{out_stem}_bands.{fmt}"
        plt_obj.savefig(str(out_path), dpi=300, bbox_inches="tight")
        typer.secho(f"✅ Written: '{out_path}'", fg=typer.colors.GREEN)


if __name__ == "__main__":
    app()
